[package]
name = "zola"
version = "0.8.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
license = "MIT"
readme = "README.md"
description = "A fast static site generator with everything built-in"
homepage = "https://www.getzola.org"
repository = "https://github.com/getzola/zola"
keywords = ["static", "site", "generator", "blog"]
# build = "build.rs"

[build-dependencies]
clap = "2"

[[bin]]
name = "zola"

[dependencies]
atty = "0.2.11"
clap = "2"
chrono = "0.4"
lazy_static = "1.1.0"
toml = "0.4"
termcolor = "1.0.4"
# Used in init to ensure the url given as base_url is a valid one
url = "1.5"
# Below is for the serve cmd
actix-files = "0.1"
actix-web = { version = "1.0", default-features = false, features = [] }
notify = "4"
ws = "0.8"
ctrlc = "3"
globset = "0.4"

site = { path = "components/site" }
errors = { path = "components/errors" }
front_matter = { path = "components/front_matter" }
utils = { path = "components/utils" }
rebuild = { path = "components/rebuild" }
config = { path = "components/config" }

[workspace]
members = [
    "components/config",
    "components/errors",
    "components/front_matter",
    "components/rebuild",
    "components/rendering",
    "components/site",
    "components/templates",
    "components/utils",
    "components/search",
    "components/imageproc",
    "components/link_checker",
    "components/library",
]

[profile.release]
lto = true
codegen-units = 1